#!/bin/bash
# AUTO-GENERATED by template-sync — do not edit directly
# To add project-specific hooks, place .sh files in ./project/
set -e
HOOK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
for f in "$HOOK_DIR/template/"*.sh; do [ -f "$f" ] && source "$f"; done
for f in "$HOOK_DIR/project/"*.sh; do [ -f "$f" ] && source "$f"; done
