"""Unit tests for CaddyConfigManager (P-0008 Scope 1)."""
import os
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

import pytest

from latarnia.caddy.manager import CaddyConfigManager
from latarnia.core.config import ConfigManager


def _make_app(name, has_web_ui=True, port=8151, app_type="service"):
    """Build a minimal registry entry stand-in."""
    return SimpleNamespace(
        name=name,
        type=app_type,
        manifest=SimpleNamespace(config=SimpleNamespace(has_web_ui=has_web_ui)),
        runtime_info=SimpleNamespace(assigned_port=port),
    )


class _FakeRegistry:
    def __init__(self, apps):
        self._apps = apps

    def get_all_apps(self):
        return self._apps


def _manager(tmp_path, apps, monkeypatch, env="dev", domain="localhost"):
    cfg = ConfigManager()
    cfg.load_config()
    cfg.config.process_manager.data_dir = str(tmp_path / "data")
    app_manager = SimpleNamespace(registry=_FakeRegistry(apps))
    monkeypatch.setenv("ENV", env)
    if domain != "localhost":
        monkeypatch.setenv(f"{env.upper()}_DOMAIN", domain)
    return CaddyConfigManager(cfg, app_manager)


def test_generate_dev_localhost_site_address(tmp_path, monkeypatch):
    mgr = _manager(tmp_path, [], monkeypatch, env="dev")
    config = mgr.generate_config()
    assert config.startswith("# Generated by Latarnia (dev)")
    assert "localhost {" in config
    # Public + catch-all blocks always present
    assert "handle /auth/* {" in config
    assert "handle /docs* {" in config
    assert "handle /openapi.json {" in config
    assert "handle /* {" in config
    assert "uri /auth/verify" in config
    assert "copy_headers X-Latarnia-User X-Latarnia-App-Role X-Latarnia-Is-Super" in config


def test_generate_writes_file(tmp_path, monkeypatch):
    mgr = _manager(tmp_path, [], monkeypatch, env="dev")
    mgr.generate_config()
    expected = tmp_path / "caddy" / "latarnia.caddyfile"
    assert expected.exists()
    assert "localhost {" in expected.read_text()


def test_prd_site_address_uses_domain_443(tmp_path, monkeypatch):
    mgr = _manager(tmp_path, [], monkeypatch, env="prd", domain="home.stanham.com")
    config = mgr.generate_config()
    assert "home.stanham.com:443 {" in config


def test_tst_site_address_uses_domain_8443(tmp_path, monkeypatch):
    mgr = _manager(tmp_path, [], monkeypatch, env="tst", domain="home.stanham.com")
    config = mgr.generate_config()
    assert "home.stanham.com:8443 {" in config


def test_web_ui_app_emits_public_and_protected_blocks(tmp_path, monkeypatch):
    apps = [_make_app("my_app", has_web_ui=True, port=8151)]
    mgr = _manager(tmp_path, apps, monkeypatch, env="dev")
    config = mgr.generate_config()
    # Public swagger (no forward_auth) — uses handle_path to strip prefix
    assert "handle_path /apps/my_app/docs* {" in config
    assert "handle_path /apps/my_app/openapi.json {" in config
    # Protected webUI block proxies to the app's port
    assert "handle_path /apps/my_app/* {" in config
    assert "reverse_proxy localhost:8151" in config


def test_app_without_web_ui_is_skipped(tmp_path, monkeypatch):
    apps = [_make_app("no_ui", has_web_ui=False, port=8152)]
    mgr = _manager(tmp_path, apps, monkeypatch, env="dev")
    config = mgr.generate_config()
    assert "/apps/no_ui/" not in config


def test_running_app_without_port_is_skipped(tmp_path, monkeypatch):
    apps = [_make_app("not_started", has_web_ui=True, port=None)]
    mgr = _manager(tmp_path, apps, monkeypatch, env="dev")
    config = mgr.generate_config()
    assert "/apps/not_started/" not in config


def test_streamlit_app_is_not_routed(tmp_path, monkeypatch):
    # Streamlit apps have their own launch/modal path — never proxied here.
    apps = [_make_app("st_app", has_web_ui=True, port=8501, app_type="streamlit")]
    mgr = _manager(tmp_path, apps, monkeypatch, env="dev")
    config = mgr.generate_config()
    assert "/apps/st_app/" not in config


def test_deregister_regenerates_without_app(tmp_path, monkeypatch):
    apps = [_make_app("my_app", port=8151)]
    mgr = _manager(tmp_path, apps, monkeypatch, env="dev")
    with patch.object(mgr, "reload", return_value=True):
        mgr.on_app_registered("my_app-1")
        assert "/apps/my_app/" in mgr._caddyfile_path().read_text()
        # Simulate the app going away, then deregister
        apps.clear()
        mgr.on_app_deregistered("my_app-1")
        assert "/apps/my_app/" not in mgr._caddyfile_path().read_text()


def test_reload_falls_back_to_admin_api_when_no_caddy_binary(tmp_path, monkeypatch):
    mgr = _manager(tmp_path, [], monkeypatch, env="dev")
    mgr.generate_config()

    class _Resp:
        status_code = 200
        text = "ok"

    with patch("latarnia.caddy.manager.shutil.which", return_value=None), \
         patch("latarnia.caddy.manager.httpx.post", return_value=_Resp()) as post:
        assert mgr.reload() is True
        assert post.call_args.kwargs["headers"]["Content-Type"] == "text/caddyfile"


def test_hooks_are_exception_safe(tmp_path, monkeypatch):
    mgr = _manager(tmp_path, [], monkeypatch, env="dev")
    with patch.object(mgr, "generate_config", side_effect=OSError("disk full")):
        # Must not raise — request handlers depend on this.
        assert mgr.on_app_registered("x") is False
        assert mgr.on_app_deregistered("x") is False
