"""Unit tests for CaddyConfigManager (P-0008 Scope 1)."""
import os
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

import pytest

from latarnia.caddy.manager import CaddyConfigManager
from latarnia.core.config import ConfigManager


def _make_app(name, has_web_ui=True, port=8151, app_type="service", public_routes=None):
    """Build a minimal registry entry stand-in."""
    return SimpleNamespace(
        name=name,
        type=app_type,
        manifest=SimpleNamespace(config=SimpleNamespace(
            has_web_ui=has_web_ui,
            public_routes=public_routes or [],
        )),
        runtime_info=SimpleNamespace(assigned_port=port),
    )


class _FakeRegistry:
    def __init__(self, apps):
        self._apps = apps

    def get_all_apps(self):
        return self._apps


def _manager(tmp_path, apps, monkeypatch, env="dev", domain="localhost"):
    cfg = ConfigManager()
    cfg.load_config()
    cfg.config.process_manager.data_dir = str(tmp_path / "data")
    app_manager = SimpleNamespace(registry=_FakeRegistry(apps))
    monkeypatch.setenv("ENV", env)
    if domain != "localhost":
        monkeypatch.setenv(f"{env.upper()}_DOMAIN", domain)
    return CaddyConfigManager(cfg, app_manager)


def test_generate_dev_localhost_site_address(tmp_path, monkeypatch):
    mgr = _manager(tmp_path, [], monkeypatch, env="dev")
    config = mgr.generate_config()
    assert config.startswith("# Generated by Latarnia (dev)")
    assert "localhost {" in config
    # Public + catch-all blocks always present
    assert "handle /auth/* {" in config
    assert "handle /docs* {" in config
    assert "handle /openapi.json {" in config
    assert "handle /* {" in config
    assert "uri /auth/verify" in config
    assert "copy_headers X-Latarnia-User X-Latarnia-App-Role X-Latarnia-Is-Super" in config


def _block_body(config: str, header: str) -> str:
    """Return the text between a `handle ... {` header and its closing brace."""
    start = config.index(header) + len(header)
    depth = 1
    i = start
    while i < len(config) and depth > 0:
        if config[i] == "{":
            depth += 1
        elif config[i] == "}":
            depth -= 1
        i += 1
    return config[start:i]


def test_api_block_has_no_forward_auth(tmp_path, monkeypatch):
    # T-0002: /api/* must be proxied straight to Latarnia (Bearer JWT or
    # session validated internally), NOT behind Caddy's session-only forward_auth.
    mgr = _manager(tmp_path, [], monkeypatch, env="dev")
    config = mgr.generate_config()
    assert "handle /api/* {" in config
    body = _block_body(config, "handle /api/* {")
    assert "forward_auth" not in body
    assert "reverse_proxy localhost:8000" in body


def test_mcp_block_present_when_enabled_no_forward_auth(tmp_path, monkeypatch):
    mgr = _manager(tmp_path, [], monkeypatch, env="dev")
    mgr.config_manager.config.mcp.enabled = True
    mgr.config_manager.config.mcp.gateway_path = "/mcp"
    config = mgr.generate_config()
    assert "handle /mcp/* {" in config
    assert "forward_auth" not in _block_body(config, "handle /mcp/* {")


def test_mcp_block_absent_when_disabled(tmp_path, monkeypatch):
    mgr = _manager(tmp_path, [], monkeypatch, env="dev")
    mgr.config_manager.config.mcp.enabled = False
    config = mgr.generate_config()
    assert "handle /mcp/* {" not in config


def test_catch_all_still_protected(tmp_path, monkeypatch):
    # The dashboard catch-all and per-app webUI keep forward_auth.
    apps = [_make_app("my_app", port=8151)]
    mgr = _manager(tmp_path, apps, monkeypatch, env="dev")
    config = mgr.generate_config()
    assert "forward_auth" in _block_body(config, "handle /* {")
    assert "uri /auth/verify" in _block_body(config, "handle /* {")
    assert "forward_auth" in _block_body(config, "handle_path /apps/my_app/* {")


def test_catch_all_redirects_unauthenticated_to_login(tmp_path, monkeypatch):
    # T-0003 / t3-001: a 401 from /auth/verify must become a 302 -> /auth/login
    # for the browser, preserving the original path as `next`.
    mgr = _manager(tmp_path, [], monkeypatch, env="dev")
    config = mgr.generate_config()
    body = _block_body(config, "handle /* {")
    assert "@auth_denied status 401" in body
    assert "handle_response @auth_denied {" in body
    assert "redir * /auth/login?next={http.request.uri.path} 302" in body


def test_app_webui_redirects_unauthenticated_to_login(tmp_path, monkeypatch):
    # T-0003 / t3-002: per-app webUI blocks get the same 401 -> login redirect.
    apps = [_make_app("my_app", port=8151)]
    mgr = _manager(tmp_path, apps, monkeypatch, env="dev")
    config = mgr.generate_config()
    body = _block_body(config, "handle_path /apps/my_app/* {")
    assert "@auth_denied status 401" in body
    assert "redir * /auth/login?next={http.request.uri.path} 302" in body


def test_machine_surfaces_have_no_login_redirect(tmp_path, monkeypatch):
    # T-0003 / t3-003: /api and /mcp must NOT redirect — machine clients get a
    # real 401, never a browser redirect.
    mgr = _manager(tmp_path, [], monkeypatch, env="dev")
    mgr.config_manager.config.mcp.enabled = True
    mgr.config_manager.config.mcp.gateway_path = "/mcp"
    config = mgr.generate_config()
    api_body = _block_body(config, "handle /api/* {")
    mcp_body = _block_body(config, "handle /mcp/* {")
    for body in (api_body, mcp_body):
        assert "redir" not in body
        assert "forward_auth" not in body


def test_generate_writes_file(tmp_path, monkeypatch):
    mgr = _manager(tmp_path, [], monkeypatch, env="dev")
    mgr.generate_config()
    expected = tmp_path / "caddy" / "latarnia.caddyfile"
    assert expected.exists()
    assert "localhost {" in expected.read_text()


def test_prd_site_address_uses_domain_443(tmp_path, monkeypatch):
    mgr = _manager(tmp_path, [], monkeypatch, env="prd", domain="home.stanham.com")
    config = mgr.generate_config()
    assert "home.stanham.com:443 {" in config


def test_tst_site_address_uses_domain_8443(tmp_path, monkeypatch):
    mgr = _manager(tmp_path, [], monkeypatch, env="tst", domain="home.stanham.com")
    config = mgr.generate_config()
    assert "home.stanham.com:8443 {" in config


def test_web_ui_app_emits_public_and_protected_blocks(tmp_path, monkeypatch):
    apps = [_make_app("my_app", has_web_ui=True, port=8151)]
    mgr = _manager(tmp_path, apps, monkeypatch, env="dev")
    config = mgr.generate_config()
    # Public swagger (no forward_auth) — uses handle_path to strip prefix
    assert "handle_path /apps/my_app/docs* {" in config
    assert "handle_path /apps/my_app/openapi.json {" in config
    # Protected webUI block proxies to the app's port
    assert "handle_path /apps/my_app/* {" in config
    assert "reverse_proxy localhost:8151" in config


def test_docs_and_openapi_blocks_strip_identity_headers(tmp_path, monkeypatch):
    # T-0004: public blocks (docs/openapi) must delete incoming X-Latarnia-*
    # headers so apps can't be spoofed via the public path.
    apps = [_make_app("my_app", has_web_ui=True, port=8151)]
    mgr = _manager(tmp_path, apps, monkeypatch, env="dev")
    config = mgr.generate_config()
    docs_body = _block_body(config, "handle_path /apps/my_app/docs* {")
    assert "header_up -X-Latarnia-User" in docs_body
    assert "header_up -X-Latarnia-App-Role" in docs_body
    assert "header_up -X-Latarnia-Is-Super" in docs_body
    assert "forward_auth" not in docs_body


def test_public_routes_block_emitted_with_strip_and_no_forward_auth(tmp_path, monkeypatch):
    # T-0004: a public_routes prefix → handle block with uri strip_prefix,
    # header deletions, and no forward_auth.
    apps = [_make_app("my_app", has_web_ui=True, port=8151, public_routes=["/b/"])]
    mgr = _manager(tmp_path, apps, monkeypatch, env="dev")
    config = mgr.generate_config()
    assert "handle /apps/my_app/b/* {" in config
    pub_body = _block_body(config, "handle /apps/my_app/b/* {")
    assert "uri strip_prefix /apps/my_app" in pub_body
    assert "header_up -X-Latarnia-User" in pub_body
    assert "header_up -X-Latarnia-App-Role" in pub_body
    assert "header_up -X-Latarnia-Is-Super" in pub_body
    assert "forward_auth" not in pub_body


def test_public_routes_emitted_before_protected_block(tmp_path, monkeypatch):
    # The public block must appear before the protected handle_path block so
    # it matches first (Caddy also sorts by specificity, but explicit order is safer).
    apps = [_make_app("my_app", has_web_ui=True, port=8151, public_routes=["/b/"])]
    mgr = _manager(tmp_path, apps, monkeypatch, env="dev")
    config = mgr.generate_config()
    pub_idx = config.index("handle /apps/my_app/b/*")
    prot_idx = config.index("handle_path /apps/my_app/* {")
    assert pub_idx < prot_idx


def test_no_public_block_when_public_routes_empty(tmp_path, monkeypatch):
    # Apps with absent/empty public_routes generate no extra handle block.
    apps = [_make_app("my_app", has_web_ui=True, port=8151, public_routes=[])]
    mgr = _manager(tmp_path, apps, monkeypatch, env="dev")
    config = mgr.generate_config()
    assert "uri strip_prefix" not in config


def test_invalid_public_route_entries_ignored(tmp_path, monkeypatch):
    # Entries that fail validation (validated by AppConfig, but defensively
    # verify the Caddy generator never emits them even if somehow passed through).
    # We test the validator through AppConfig directly.
    from latarnia.managers.app_manager import AppConfig
    cfg = AppConfig(public_routes=["/", "/b/", "no-slash", "/docs", "/health", ""])
    # Only "/b/" should survive
    assert cfg.public_routes == ["/b/"]


def test_app_without_web_ui_is_skipped(tmp_path, monkeypatch):
    apps = [_make_app("no_ui", has_web_ui=False, port=8152)]
    mgr = _manager(tmp_path, apps, monkeypatch, env="dev")
    config = mgr.generate_config()
    assert "/apps/no_ui/" not in config


def test_running_app_without_port_is_skipped(tmp_path, monkeypatch):
    apps = [_make_app("not_started", has_web_ui=True, port=None)]
    mgr = _manager(tmp_path, apps, monkeypatch, env="dev")
    config = mgr.generate_config()
    assert "/apps/not_started/" not in config


def test_streamlit_app_is_not_routed(tmp_path, monkeypatch):
    # Streamlit apps have their own launch/modal path — never proxied here.
    apps = [_make_app("st_app", has_web_ui=True, port=8501, app_type="streamlit")]
    mgr = _manager(tmp_path, apps, monkeypatch, env="dev")
    config = mgr.generate_config()
    assert "/apps/st_app/" not in config


def test_deregister_regenerates_without_app(tmp_path, monkeypatch):
    apps = [_make_app("my_app", port=8151)]
    mgr = _manager(tmp_path, apps, monkeypatch, env="dev")
    with patch.object(mgr, "reload", return_value=True):
        mgr.on_app_registered("my_app-1")
        assert "/apps/my_app/" in mgr._caddyfile_path().read_text()
        # Simulate the app going away, then deregister
        apps.clear()
        mgr.on_app_deregistered("my_app-1")
        assert "/apps/my_app/" not in mgr._caddyfile_path().read_text()


def test_reload_falls_back_to_admin_api_when_no_caddy_binary(tmp_path, monkeypatch):
    mgr = _manager(tmp_path, [], monkeypatch, env="dev")
    mgr.generate_config()

    class _Resp:
        status_code = 200
        text = "ok"

    with patch("latarnia.caddy.manager.shutil.which", return_value=None), \
         patch("latarnia.caddy.manager.httpx.post", return_value=_Resp()) as post:
        assert mgr.reload() is True
        assert post.call_args.kwargs["headers"]["Content-Type"] == "text/caddyfile"


def test_hooks_are_exception_safe(tmp_path, monkeypatch):
    mgr = _manager(tmp_path, [], monkeypatch, env="dev")
    with patch.object(mgr, "generate_config", side_effect=OSError("disk full")):
        # Must not raise — request handlers depend on this.
        assert mgr.on_app_registered("x") is False
        assert mgr.on_app_deregistered("x") is False
